#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright© 2023 LinuxUsersLinuxMint
# PyTerm Tüm Hakları GPL(Genel Kamu Lisansı) altında korunmaktadır.
# PyTerm All Rights Reserved under the GPL(General Public License).
# Bu Yazılımın Bir Kopyası GİTHUB da yayınlanmaktadır Görüntülemek için: https://github.com/LinuxUsersLinuxMint/LinuxUsersLinuxMint
# A Copy of This Software is published on GITHUB To view: https://github.com/LinuxUsersLinuxMint/LinuxUsersLinuxMint
from File.filePath.filePath import *
from File.FileMng.FileAdd.fileadd import *
from File.FileMng.FileList.filelist import *
from File.FileMng.FileRemove.fileremove import *
from File.FileMng.FileRename.filerename import *
from File.FileMng.VarRename.varrename import *
from Program.InfoProgram.infoprogram import *
from Program.PyTempClear.pytempclear import *
from Program.PyTermUpdateAssistans.pytermupdateass import *
from Program.Help.help import *
from Program.ConfigSoftware.ConfigSuperUser.configsu import *
from Program.ConfigSoftware.ConfigUpdate.cfg_update import *

while True:
    process=str(input('Enter The Process: '))

    if process=="FileAdd":
        FileAdd()
        continue
    elif process=="FileList":
        FileList()
        continue
    elif process=="FileRemove":
        FileRemove()
        continue
    elif process=="FileRename":
        FileRename()
        continue
    elif process=="VarRename":
        VarRename()
        continue
    elif process=="InfoProgram":
        InfoProgram()
        continue
    elif process=="PyTempClear":
        PyTempClear()
        continue
    elif process=="PyTermUpdateAssistans":
        PyTermUpdateAssistans()
        continue
    elif process=="Help":
        Help()
        continue
    elif process=="Config":
        config_process=str(input('Which config do you want to edit?: '))
        if config_process=="cfg_update_":
            cfg_update_()
            continue
        elif config_process=="cfg_super_usr_":
            cfg_super_user_()
            continue
        continue
    elif process=="exit":
        exit()