#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright© 2023 LinuxUsersLinuxMint
# PyTerm Tüm Hakları GPL(Genel Kamu Lisansı) altında korunmaktadır.
# PyTerm All Rights Reserved under the GPL(General Public License).
# Bu Yazılımın Bir Kopyası GİTHUB da yayınlanmaktadır Görüntülemek için: https://github.com/LinuxUsersLinuxMint/LinuxUsersLinuxMint
# A Copy of This Software is published on GITHUB To view: https://github.com/LinuxUsersLinuxMint/LinuxUsersLinuxMint
from Library.pytermlibrary import *

while True:
    process=str(input('Enter The Process: '))

    if process=="FileAdd":
        FileAdd()
        continue
    elif process=="FileList":
        FileList()
        continue
    elif process=="FileRemove":
        FileRemove()
        continue
    elif process=="FileRename":
        FileRename()
        continue
    elif process=="VarRename":
        VarRename()
        continue
    elif process=="InfoProgram":
        InfoProgram()
        continue
    elif process=="PyTempClear":
        PyTempClear()
        continue
    elif process=="PyTermUpdateAssistans":
        PyTermUpdateAssistans()
        continue
    elif process=="RunProgram":
        beta_runprogram()
        continue
    elif process=="Help":
        Help()
        continue
    elif process=="Config":
        config_process=str(input('Which config do you want to edit?: '))
        if config_process=="cfg_update_":
            cfg_update_()
        elif config_process=="cfg_super_usr_":
            cfg_super_user_()
        continue
    elif process=="FileFormat":
        file_dictf()
        continue
    elif process=="Compatible_os" or process=="Compatible OS":
        compatible_os()
        continue
    elif process=="exit":
        exit()