#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright© 2023 LinuxUsersLinuxMint
# PyTerm Tüm Hakları GPL(Genel Kamu Lisansı) altında korunmaktadır.
# PyTerm All Rights Reserved under the GPL(General Public License).
# Bu Yazılımın Bir Kopyası GİTHUB da yayınlanmaktadır Görüntülemek için: https://github.com/LinuxUsersLinuxMint/LinuxUsersLinuxMint
# A Copy of This Software is published on GITHUB To view: https://github.com/LinuxUsersLinuxMint/LinuxUsersLinuxMint
from File.filePath.filePath import *
from File.FileMng.FileAdd.fileadd import *
from File.FileMng.FileList.filelist import *
from File.FileMng.FileRemove.fileremove import *
from File.FileMng.FileRename.filerename import *
from File.FileMng.VarRename.varrename import *

while True:
    process=str(input('İslem giriniz: '))

    if process=="FileAdd":
        FileAdd()
        continue
    elif process=="FileList":
        FileList()
        continue
    elif process=="FileRemove":
        FileRemove()
        continue
    elif process=="FileRename":
        FileRename()
        continue
    elif process=="VarRename":
        VarRename()
        continue