mkdir LxProgram
mkdir LxProgram/PyTerm
mkdir LxProgram/PyTerm/File
mkdir LxProgram/PyTerm/File/FileMng
mkdir LxProgram/PyTerm/File/FileMng/FileAdd
mkdir LxProgram/PyTerm/File/FileMng/FileRemove
mkdir LxProgram/PyTerm/File/FileMng/FileList
mkdir LxProgram/PyTerm/File/FileMng/FileRename
mkdir LxProgram/PyTerm/File/FileMng/VarRename
mkdir LxProgram/PyTerm/File/filePath
mkdir LxProgram/PyTerm/Help
mkdir LxProgram/PyTerm/InfoProject
mkdir LxProgram/PyTerm/Program
mkdir LxProgram/PyTerm/Program/InfoProgram
mkdir LxProgram/PyTerm/Program/PyTempClear
mkdir LxProgram/PyTerm/Program/PyTermUpdateAssistans
mkdir LxProgram/PyTerm/Program/Help
mkdir LxProgram/PyTerm/Program/RunProgram
chmod a+x LxProgram