cp PyTerm LxProgram/PyTerm/
chmod a+x LxProgram/PyTerm/PyTerm
cp File/filePath/filePath.py LxProgram/PyTerm/File/filePath/
chmod a+x LxProgram/PyTerm/File/filePath/filePath.py
cp File/FileMng/FileAdd/fileadd.py LxProgram/PyTerm/File/FileMng/FileAdd/
chmod a+x LxProgram/PyTerm/File/FileMng/FileAdd/fileadd.py
cp File/FileMng/FileRemove/fileremove.py LxProgram/PyTerm/File/FileMng/FileRemove/
chmod a+x LxProgram/PyTerm/File/FileMng/FileRemove/fileremove.py
cp File/FileMng/FileList/filelist.py LxProgram/PyTerm/File/FileMng/FileList/
chmod a+x LxProgram/PyTerm/File/FileMng/FileList/filelist.py
cp File/FileMng/FileRename/filerename.py LxProgram/PyTerm/File/FileMng/FileRename/
chmod a+x LxProgram/PyTerm/File/FileMng/FileRename/filerename.py
cp File/FileMng/VarRename/varrename.py LxProgram/PyTerm/File/FileMng/VarRename/
chmod a+x LxProgram/PyTerm/File/FileMng/VarRename/varrename.py
cp Help/howtoinstall.txt LxProgram/PyTerm/Help/
chmod a+x LxProgram/PyTerm/Help/howtoinstall.txt
cp InfoProject/info.py LxProgram/PyTerm/InfoProject/
chmod a+x LxProgram/PyTerm/InfoProject/info.py
cp Program/InfoProgram/infoprogram.py LxProgram/PyTerm/Program/InfoProgram/
chmod a+x LxProgram/PyTerm/Program/InfoProgram/infoprogram.py
cp Program/PyTempClear/pytempclear.py LxProgram/PyTerm/Program/PyTempClear/
chmod a+x LxProgram/PyTerm/Program/PyTempClear/pytempclear.py
cp Program/PyTermUpdateAssistans/pytermupdateass.py LxProgram/PyTerm/Program/PyTermUpdateAssistans
chmod a+x LxProgram/PyTerm/Program/PyTermUpdateAssistans/pytermupdateass.py
cp Program/Help/help.py LxProgram/PyTerm/Program/Help
chmod a+x LxProgram/PyTerm/Program/Help/help.py
cp Program/RunProgram/runprogram.py LxProgram/PyTerm/Program/RunProgram
chmod a+x LxProgram/PyTerm/Program/RunProgram/runprogram.py
cp Program/RunProgram/WarningsandInstruction.txt LxProgram/PyTerm/Program/RunProgram
chmod a+x LxProgram/PyTerm/Program/RunProgram/WarningsandInstruction.txt