#!/usr/bin/sh
cp PyTerm LxProgram/PyTerm/
chmod a+x LxProgram/PyTerm/PyTerm
cp File/filePath/filePath.py LxProgram/PyTerm/File/filePath/
chmod a+x LxProgram/PyTerm/File/filePath/filePath.py
cp File/FileMng/FileAdd/fileadd.py LxProgram/PyTerm/File/FileMng/FileAdd/
chmod a+x LxProgram/PyTerm/File/FileMng/FileAdd/fileadd.py
cp File/FileMng/FileRemove/fileremove.py LxProgram/PyTerm/File/FileMng/FileRemove/
chmod a+x LxProgram/PyTerm/File/FileMng/FileRemove/fileremove.py
cp File/FileMng/FileList/filelist.py LxProgram/PyTerm/File/FileMng/FileList/
chmod a+x LxProgram/PyTerm/File/FileMng/FileList/filelist.py
cp File/FileMng/FileRename/filerename.py LxProgram/PyTerm/File/FileMng/FileRename/
chmod a+x LxProgram/PyTerm/File/FileMng/FileRename/filerename.py
cp File/FileMng/VarRename/varrename.py LxProgram/PyTerm/File/FileMng/VarRename/
chmod a+x LxProgram/PyTerm/File/FileMng/VarRename/varrename.py
cp Help/howtoinstall.txt LxProgram/PyTerm/Help/
chmod a+x LxProgram/PyTerm/Help/howtoinstall.txt
cp InfoProject/info.py LxProgram/PyTerm/InfoProject/
chmod a+x LxProgram/PyTerm/InfoProject/info.py
cp Program/InfoProgram/infoprogram.py LxProgram/PyTerm/Program/InfoProgram/
chmod a+x LxProgram/PyTerm/Program/InfoProgram/infoprogram.py
cp Program/PyTempClear/pytempclear.py LxProgram/PyTerm/Program/PyTempClear/
chmod a+x LxProgram/PyTerm/Program/PyTempClear/pytempclear.py
cp Program/PyTermUpdateAssistans/pytermupdateass.py LxProgram/PyTerm/Program/PyTermUpdateAssistans
chmod a+x LxProgram/PyTerm/Program/PyTermUpdateAssistans/pytermupdateass.py
cp Program/Help/help.py LxProgram/PyTerm/Program/Help
chmod a+x LxProgram/PyTerm/Program/Help/help.py
cp Program/RunProgram/runprogram.py LxProgram/PyTerm/Program/RunProgram
chmod a+x LxProgram/PyTerm/Program/RunProgram/runprogram.py
cp Program/RunProgram/WarningsandInstructions.txt LxProgram/PyTerm/Program/RunProgram
chmod a+x LxProgram/PyTerm/Program/RunProgram/WarningsandInstructions.txt
cp Program/ConfigSoftware/ConfigSuperUser/configsu.py LxProgram/PyTerm/Program/ConfigSoftware/ConfigSuperUser
chmod a+x LxProgram/PyTerm/Program/ConfigSoftware/ConfigSuperUser/configsu.py
cp Program/ConfigSoftware/ConfigUpdate/cfg_update.py LxProgram/PyTerm/Program/ConfigSoftware/ConfigUpdate
chmod a+x LxProgram/PyTerm/Program/ConfigSoftware/ConfigUpdate/cfg_update.py
cp software.cfgpt LxProgram/PyTerm
chmod a+x LxProgram/PyTerm/software.cfgpt
cp Program/Compatibleos/compatibleos.py LxProgram/PyTerm/Program/Compatibleos
chmod a+x LxProgram/PyTerm/Program/Compatibleos/compatibleos.py
cp File/FileMng/Filedictformat/filedictformat.py LxProgram/PyTerm/File/FileMng/Filedictformat
chmod a+x LxProgram/PyTerm/File/FileMng/Filedictformat/filedictformat.py
cp Library/pytermlibrary.py LxProgram/PyTerm/Library
chmod a+x LxProgram/PyTerm/Library/pytermlibrary.py
